export const TEAMS = [
  { abbr: 'MEX', name: 'México' },
  { abbr: 'AFS', name: 'África do Sul' },
  { abbr: 'COR', name: 'Coreia do Sul' },
  { abbr: 'TCH', name: 'Tchéquia' },
  { abbr: 'CAN', name: 'Canadá' },
  { abbr: 'BOS', name: 'Bósnia' },
  { abbr: 'CAT', name: 'Catar' },
  { abbr: 'SUI', name: 'Suíça' },
  { abbr: 'BRA', name: 'Brasil' },
  { abbr: 'MAR', name: 'Marrocos' },
  { abbr: 'HAI', name: 'Haiti' },
  { abbr: 'ESC', name: 'Escócia' },
  { abbr: 'EUA', name: 'Estados Unidos' },
  { abbr: 'PAR', name: 'Paraguai' },
  { abbr: 'AUS', name: 'Austrália' },
  { abbr: 'TUR', name: 'Turquia' },
  { abbr: 'ALE', name: 'Alemanha' },
  { abbr: 'CUR', name: 'Curaçao' },
  { abbr: 'CDM', name: 'Costa do Marfim' },
  { abbr: 'EQU', name: 'Equador' },
  { abbr: 'HOL', name: 'Holanda' },
  { abbr: 'JAP', name: 'Japão' },
  { abbr: 'SUE', name: 'Suécia' },
  { abbr: 'TUN', name: 'Tunísia' },
  { abbr: 'BEL', name: 'Bélgica' },
  { abbr: 'EGI', name: 'Egito' },
  { abbr: 'IRA', name: 'Irã' },
  { abbr: 'NZE', name: 'Nova Zelândia' },
  { abbr: 'ESP', name: 'Espanha' },
  { abbr: 'CAB', name: 'Cabo Verde' },
  { abbr: 'SAU', name: 'Arábia Saudita' },
  { abbr: 'URU', name: 'Uruguai' },
  { abbr: 'FRA', name: 'França' },
  { abbr: 'SEN', name: 'Senegal' },
  { abbr: 'IRQ', name: 'Iraque' },
  { abbr: 'NOR', name: 'Noruega' },
  { abbr: 'ARG', name: 'Argentina' },
  { abbr: 'AGL', name: 'Angola' },
  { abbr: 'AUT', name: 'Áustria' },
  { abbr: 'JOR', name: 'Jordânia' },
  { abbr: 'POR', name: 'Portugal' },
  { abbr: 'RDC', name: 'RD Congo' },
  { abbr: 'UZB', name: 'Uzbequistão' },
  { abbr: 'COL', name: 'Colômbia' },
  { abbr: 'ING', name: 'Inglaterra' },
  { abbr: 'CRO', name: 'Croácia' },
  { abbr: 'GAN', name: 'Gana' },
  { abbr: 'PAN', name: 'Panamá' },
];

export const PHASES = [
  { key: 'groups', label: '1ª Fase', matchCount: 72, order: 0 },
  { key: 'segunda_fase', label: '2ª Fase', matchSlots: 32, matchCount: 16, order: 1 },
  { key: 'oitavas', label: 'Oitavas de Final', matchSlots: 16, matchCount: 8, order: 2 },
  { key: 'quartas', label: 'Quartas de Final', matchSlots: 8, matchCount: 4, order: 3 },
  { key: 'semifinal', label: 'Semifinal', matchSlots: 4, matchCount: 2, order: 4 },
  { key: 'terceiro_lugar', label: '3º Lugar', matchSlots: 2, matchCount: 1, order: 5 },
  { key: 'final', label: 'Final', matchSlots: 2, matchCount: 1, order: 6 },
];

export const MATCHES = [
  // Round 1 - 1ª Rodada
  { round: 1, matchNum: 1, homeTeam: 'MEX', awayTeam: 'AFS', homeName: 'México', awayName: 'África do Sul', phase: 'groups' },
  { round: 1, matchNum: 2, homeTeam: 'COR', awayTeam: 'TCH', homeName: 'Coreia do Sul', awayName: 'Tchéquia', phase: 'groups' },
  { round: 1, matchNum: 3, homeTeam: 'CAN', awayTeam: 'BOS', homeName: 'Canadá', awayName: 'Bósnia', phase: 'groups' },
  { round: 1, matchNum: 4, homeTeam: 'CAT', awayTeam: 'SUI', homeName: 'Catar', awayName: 'Suíça', phase: 'groups' },
  { round: 1, matchNum: 5, homeTeam: 'BRA', awayTeam: 'MAR', homeName: 'Brasil', awayName: 'Marrocos', phase: 'groups' },
  { round: 1, matchNum: 6, homeTeam: 'HAI', awayTeam: 'ESC', homeName: 'Haiti', awayName: 'Escócia', phase: 'groups' },
  { round: 1, matchNum: 7, homeTeam: 'EUA', awayTeam: 'PAR', homeName: 'Estados Unidos', awayName: 'Paraguai', phase: 'groups' },
  { round: 1, matchNum: 8, homeTeam: 'AUS', awayTeam: 'TUR', homeName: 'Austrália', awayName: 'Turquia', phase: 'groups' },
  { round: 1, matchNum: 9, homeTeam: 'ALE', awayTeam: 'CUR', homeName: 'Alemanha', awayName: 'Curaçao', phase: 'groups' },
  { round: 1, matchNum: 10, homeTeam: 'CDM', awayTeam: 'EQU', homeName: 'Costa do Marfim', awayName: 'Equador', phase: 'groups' },
  { round: 1, matchNum: 11, homeTeam: 'HOL', awayTeam: 'JAP', homeName: 'Holanda', awayName: 'Japão', phase: 'groups' },
  { round: 1, matchNum: 12, homeTeam: 'SUE', awayTeam: 'TUN', homeName: 'Suécia', awayName: 'Tunísia', phase: 'groups' },
  { round: 1, matchNum: 13, homeTeam: 'BEL', awayTeam: 'EGI', homeName: 'Bélgica', awayName: 'Egito', phase: 'groups' },
  { round: 1, matchNum: 14, homeTeam: 'IRA', awayTeam: 'NZE', homeName: 'Irã', awayName: 'Nova Zelândia', phase: 'groups' },
  { round: 1, matchNum: 15, homeTeam: 'ESP', awayTeam: 'CAB', homeName: 'Espanha', awayName: 'Cabo Verde', phase: 'groups' },
  { round: 1, matchNum: 16, homeTeam: 'SAU', awayTeam: 'URU', homeName: 'Arábia Saudita', awayName: 'Uruguai', phase: 'groups' },
  { round: 1, matchNum: 17, homeTeam: 'FRA', awayTeam: 'SEN', homeName: 'França', awayName: 'Senegal', phase: 'groups' },
  { round: 1, matchNum: 18, homeTeam: 'IRQ', awayTeam: 'NOR', homeName: 'Iraque', awayName: 'Noruega', phase: 'groups' },
  { round: 1, matchNum: 19, homeTeam: 'ARG', awayTeam: 'AGL', homeName: 'Argentina', awayName: 'Angola', phase: 'groups' },
  { round: 1, matchNum: 20, homeTeam: 'AUT', awayTeam: 'JOR', homeName: 'Áustria', awayName: 'Jordânia', phase: 'groups' },
  { round: 1, matchNum: 21, homeTeam: 'POR', awayTeam: 'RDC', homeName: 'Portugal', awayName: 'RD Congo', phase: 'groups' },
  { round: 1, matchNum: 22, homeTeam: 'UZB', awayTeam: 'COL', homeName: 'Uzbequistão', awayName: 'Colômbia', phase: 'groups' },
  { round: 1, matchNum: 23, homeTeam: 'ING', awayTeam: 'CRO', homeName: 'Inglaterra', awayName: 'Croácia', phase: 'groups' },
  { round: 1, matchNum: 24, homeTeam: 'GAN', awayTeam: 'PAN', homeName: 'Gana', awayName: 'Panamá', phase: 'groups' },

  // Round 2 - 2ª Rodada
  { round: 2, matchNum: 1, homeTeam: 'TCH', awayTeam: 'AFS', homeName: 'Tchéquia', awayName: 'África do Sul', phase: 'groups' },
  { round: 2, matchNum: 2, homeTeam: 'MEX', awayTeam: 'COR', homeName: 'México', awayName: 'Coreia do Sul', phase: 'groups' },
  { round: 2, matchNum: 3, homeTeam: 'SUI', awayTeam: 'BOS', homeName: 'Suíça', awayName: 'Bósnia', phase: 'groups' },
  { round: 2, matchNum: 4, homeTeam: 'CAN', awayTeam: 'CAT', homeName: 'Canadá', awayName: 'Catar', phase: 'groups' },
  { round: 2, matchNum: 5, homeTeam: 'ESC', awayTeam: 'MAR', homeName: 'Escócia', awayName: 'Marrocos', phase: 'groups' },
  { round: 2, matchNum: 6, homeTeam: 'BRA', awayTeam: 'HAI', homeName: 'Brasil', awayName: 'Haiti', phase: 'groups' },
  { round: 2, matchNum: 7, homeTeam: 'EUA', awayTeam: 'AUS', homeName: 'Estados Unidos', awayName: 'Austrália', phase: 'groups' },
  { round: 2, matchNum: 8, homeTeam: 'TUR', awayTeam: 'PAR', homeName: 'Turquia', awayName: 'Paraguai', phase: 'groups' },
  { round: 2, matchNum: 9, homeTeam: 'ALE', awayTeam: 'CDM', homeName: 'Alemanha', awayName: 'Costa do Marfim', phase: 'groups' },
  { round: 2, matchNum: 10, homeTeam: 'EQU', awayTeam: 'CUR', homeName: 'Equador', awayName: 'Curaçao', phase: 'groups' },
  { round: 2, matchNum: 11, homeTeam: 'HOL', awayTeam: 'SUE', homeName: 'Holanda', awayName: 'Suécia', phase: 'groups' },
  { round: 2, matchNum: 12, homeTeam: 'TUN', awayTeam: 'JAP', homeName: 'Tunísia', awayName: 'Japão', phase: 'groups' },
  { round: 2, matchNum: 13, homeTeam: 'BEL', awayTeam: 'IRA', homeName: 'Bélgica', awayName: 'Irã', phase: 'groups' },
  { round: 2, matchNum: 14, homeTeam: 'NZE', awayTeam: 'EGI', homeName: 'Nova Zelândia', awayName: 'Egito', phase: 'groups' },
  { round: 2, matchNum: 15, homeTeam: 'ESP', awayTeam: 'SAU', homeName: 'Espanha', awayName: 'Arábia Saudita', phase: 'groups' },
  { round: 2, matchNum: 16, homeTeam: 'URU', awayTeam: 'CAB', homeName: 'Uruguai', awayName: 'Cabo Verde', phase: 'groups' },
  { round: 2, matchNum: 17, homeTeam: 'FRA', awayTeam: 'IRQ', homeName: 'França', awayName: 'Iraque', phase: 'groups' },
  { round: 2, matchNum: 18, homeTeam: 'NOR', awayTeam: 'SEN', homeName: 'Noruega', awayName: 'Senegal', phase: 'groups' },
  { round: 2, matchNum: 19, homeTeam: 'ARG', awayTeam: 'AUT', homeName: 'Argentina', awayName: 'Áustria', phase: 'groups' },
  { round: 2, matchNum: 20, homeTeam: 'JOR', awayTeam: 'AGL', homeName: 'Jordânia', awayName: 'Angola', phase: 'groups' },
  { round: 2, matchNum: 21, homeTeam: 'POR', awayTeam: 'UZB', homeName: 'Portugal', awayName: 'Uzbequistão', phase: 'groups' },
  { round: 2, matchNum: 22, homeTeam: 'COL', awayTeam: 'RDC', homeName: 'Colômbia', awayName: 'RD Congo', phase: 'groups' },
  { round: 2, matchNum: 23, homeTeam: 'ING', awayTeam: 'GAN', homeName: 'Inglaterra', awayName: 'Gana', phase: 'groups' },
  { round: 2, matchNum: 24, homeTeam: 'PAN', awayTeam: 'CRO', homeName: 'Panamá', awayName: 'Croácia', phase: 'groups' },

  // Round 3 - 3ª Rodada
  { round: 3, matchNum: 1, homeTeam: 'AFS', awayTeam: 'COR', homeName: 'África do Sul', awayName: 'Coreia do Sul', phase: 'groups' },
  { round: 3, matchNum: 2, homeTeam: 'TCH', awayTeam: 'MEX', homeName: 'Tchéquia', awayName: 'México', phase: 'groups' },
  { round: 3, matchNum: 3, homeTeam: 'SUI', awayTeam: 'CAN', homeName: 'Suíça', awayName: 'Canadá', phase: 'groups' },
  { round: 3, matchNum: 4, homeTeam: 'BOS', awayTeam: 'CAT', homeName: 'Bósnia', awayName: 'Catar', phase: 'groups' },
  { round: 3, matchNum: 5, homeTeam: 'MAR', awayTeam: 'HAI', homeName: 'Marrocos', awayName: 'Haiti', phase: 'groups' },
  { round: 3, matchNum: 6, homeTeam: 'BRA', awayTeam: 'ESC', homeName: 'Brasil', awayName: 'Escócia', phase: 'groups' },
  { round: 3, matchNum: 7, homeTeam: 'TUR', awayTeam: 'EUA', homeName: 'Turquia', awayName: 'Estados Unidos', phase: 'groups' },
  { round: 3, matchNum: 8, homeTeam: 'PAR', awayTeam: 'AUS', homeName: 'Paraguai', awayName: 'Austrália', phase: 'groups' },
  { round: 3, matchNum: 9, homeTeam: 'EQU', awayTeam: 'ALE', homeName: 'Equador', awayName: 'Alemanha', phase: 'groups' },
  { round: 3, matchNum: 10, homeTeam: 'CUR', awayTeam: 'CDM', homeName: 'Curaçao', awayName: 'Costa do Marfim', phase: 'groups' },
  { round: 3, matchNum: 11, homeTeam: 'TUN', awayTeam: 'HOL', homeName: 'Tunísia', awayName: 'Holanda', phase: 'groups' },
  { round: 3, matchNum: 12, homeTeam: 'JAP', awayTeam: 'SUE', homeName: 'Japão', awayName: 'Suécia', phase: 'groups' },
  { round: 3, matchNum: 13, homeTeam: 'EGI', awayTeam: 'IRA', homeName: 'Egito', awayName: 'Irã', phase: 'groups' },
  { round: 3, matchNum: 14, homeTeam: 'NZE', awayTeam: 'BEL', homeName: 'Nova Zelândia', awayName: 'Bélgica', phase: 'groups' },
  { round: 3, matchNum: 15, homeTeam: 'CAB', awayTeam: 'SAU', homeName: 'Cabo Verde', awayName: 'Arábia Saudita', phase: 'groups' },
  { round: 3, matchNum: 16, homeTeam: 'URU', awayTeam: 'ESP', homeName: 'Uruguai', awayName: 'Espanha', phase: 'groups' },
  { round: 3, matchNum: 17, homeTeam: 'SEN', awayTeam: 'IRQ', homeName: 'Senegal', awayName: 'Iraque', phase: 'groups' },
  { round: 3, matchNum: 18, homeTeam: 'NOR', awayTeam: 'FRA', homeName: 'Noruega', awayName: 'França', phase: 'groups' },
  { round: 3, matchNum: 19, homeTeam: 'JOR', awayTeam: 'ARG', homeName: 'Jordânia', awayName: 'Argentina', phase: 'groups' },
  { round: 3, matchNum: 20, homeTeam: 'AGL', awayTeam: 'AUT', homeName: 'Angola', awayName: 'Áustria', phase: 'groups' },
  { round: 3, matchNum: 21, homeTeam: 'RDC', awayTeam: 'UZB', homeName: 'RD Congo', awayName: 'Uzbequistão', phase: 'groups' },
  { round: 3, matchNum: 22, homeTeam: 'COL', awayTeam: 'POR', homeName: 'Colômbia', awayName: 'Portugal', phase: 'groups' },
  { round: 3, matchNum: 23, homeTeam: 'CRO', awayTeam: 'GAN', homeName: 'Croácia', awayName: 'Gana', phase: 'groups' },
  { round: 3, matchNum: 24, homeTeam: 'PAN', awayTeam: 'ING', homeName: 'Panamá', awayName: 'Inglaterra', phase: 'groups' },
];
